### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Thermatix** [yomimono/example-unikernels#1]
I realise this is not the place for this but the only other way to contact you is through twitter and I don't use twitter. I read your blog on unikernals and I found it interesting. I was wondering if it was possible to build a unikernal to run sinatra or ruby-on-rails or any other web framework, if so could you point me in the right direction? 
I've googled (I can't believe that's actually a verb but it fits) but can't find much on building a unikernal specifically for running ruby based framework applications.

Again, I apologise for the place ment of this question but I wasn't sure where else to put this.

**Comment by yomimono** [comment]
We get questions like this every now and again on the MirageOS-devel mailing list: http://lists.xenproject.org/cgi-bin/mailman/listinfo/mirageos-devel .  There's also a #mirage on the Freenode IRC network ( https://freenode.net/ ), although it's usually pretty quiet; usually #ocaml is a better place for questions and discussion. 

If you wanted to use Mirage specifically, you might want to look into OCaml web frameworks.  One I know of is Eliom: https://github.com/ocsigen/eliom .  I don't know whether anyone's running Eliom applications on Mirage at the moment and I don't have any experience of Eliom specifically, so I can't provide much more advice than that, but I think anything that anyone would be able to get up and working would be of interest to the community generally.

If you're more interested in getting different existing software stacks to run in a unified environment, you might want to look into the more general work of the folks who are working on rump kernels.  They've recently been talking about Ruby on Rails ( http://permalink.gmane.org/gmane.comp.rumpkernel.user/716 ), and they have a generally active mailing list at rumpkernel-users@lists.sourceforge.net (web interface at http://blog.gmane.org/gmane.comp.rumpkernel.user ).  

You might also be interested in MiniOS ( http://wiki.xen.org/wiki/Mini-OS ) which is foundational for Mirage's approach to running OCaml code on Xen; a number of non-Mirage projects like HaLVM ( https://github.com/GaloisInc/HaLVM ) and ClickOS ( http://conferences.sigcomm.org/sigcomm/2013/papers/hotsdn/p67.pdf ) run on top of MiniOS, although I don't know of any that are targeted in the space you're interested in (which doesn't mean they don't exist)!

**Comment by Thermatix** [comment]
Thanks very much, I'll take a look at this tonight!
